### DISCUSSION TITLE
Support 'windows' like tmuxinator + custom icons?

### DISCUSSION THREAD

**Discussion by rodhash** [joshmedeski/sesh#245] [Q&A]
Hey

1. Not sure this is planned but if Sesh would support creation of tmux "windows", this would be cool.

Tmuxinator seems to be slower compared to sesh-only, I don't have detailed measurements but working on my personal mac and MBP from company I can see some speed difference between.

Is this something planned to?

2. Icons are hard coded, right? For Sesh, Tmuxinator, Conf.. perhaps a custom icon would be nice to have, something like this:
```toml
[[session]]
name = ".."
path = ".."
startup_command = ".."
icon = ".."
```

Thanks.
