### DISCUSSION TITLE
Two sessions with same name

### DISCUSSION THREAD

**Discussion by riza-khan** [joshmedeski/sesh#268] [Q&A] [answered]
I'm on two different folders:

`/folder 1/mainline` do: `sesh connect .`
`/folder 2/mainline` do: `sesh connect .`

When you do the second `sesh connect .`, it connects to folder 1 session, doesn't create a new session for folder 2's mainline folder.

Is there a workaround for this in Sesh?

Thank you!

**Comment by joshmedeski** [comment, marked as answer]
Yes, I recommend using a custom config to ensure you always know which `mainline` you are in:

```toml
[[session]]
name = "folder 1 mainline"
path = "/folder 1/mainline"

[[session]]
name = "folder 2 mainline"
path = "/folder 2/mainline"
```

I would warn you that having two folders with the same name is tricky business in general. I like using git worktrees for copies of the same project as sesh already supports worktree naming and would be a more scalable solution.
