### ISSUE TITLE
Shortcut per session as configuration

### ISSUE THREAD

**Issue by rtalexk** [joshmedeski/sesh#107]
### What would you like sesh to do?

I've been using Sesh for a while and it is extraordinary, it solves a pain I was having.

It is pretty common that I always navigate to the same sessions (the project I'm working on, my dotfiles, my notes, etc). And every time I want to switch between them I have to `<prefix>B + K` and then some chars to focus the right session.

It would be amazing if you could assign a shortcut to each session in the configuration file as below, this would streamline the navigation a lot.

```toml
[[session]]
name = "Downloads 📥"
path = "~/Downloads"
startup_command = "ls"
shortcut = "<C-1>"

[[session]]
name = "tmux config"
path = "~/c/dotfiles/.config/tmux"
startup_command = "nvim tmux.conf"
shortcut = "<C-2>"
```
