### ISSUE TITLE
Path subsitution

### ISSUE THREAD

**Issue by joshmedeski** [joshmedeski/sesh#129]
### What would you like sesh to do?

As a user, I want to define global substitution rules, so I can create custom session name rules to improve my session names and create a more streamlined workflow.

# Example

- `~/c/dotfiles/.config/neovim` could be changed to `💻 neovim` (replacing `~/c/dotfiles/.config`)

```toml
[namer]
[[find_and_replace]]
find = "~/c/dotfiles/.config/"
replace = "💻 "
```
