### ISSUE TITLE
Disable Startup Command

### ISSUE THREAD

**Issue by Catgroove** [joshmedeski/sesh#153]
### What would you like sesh to do?

Apologies if this is already possible.

When using a default session along with a startup command, I would like to be able to clear that on a session basis using something along the lines of `startup_command = ""`.

**Why?**

For my default startup command, I typically want to always run `nvim`, but for some specific sessions, I would just like to be placed in the directory, for example when I'm opening up my folder of git repositories.

**Comment by joshmedeski** [comment]
I recommend setting it to something like `ls`. That's what I do in this situation.

**Comment by Catgroove** [comment]
That works. Feels a bit hacky but good enough for now.

**Comment by joshmedeski** [comment]
Do you have any suggestions?

We could detect if the startup command is an empty value then don't run the default command. Not sure if that's very intuitive

**Comment by joshmedeski** [comment]
What do you think of this 

```toml
[[session]]
name = "fish config"
path = "~/c/dotfiles/.config/fish"
disable_startup_command = true
```

It should be trivial to implement, but I think adding some sort of simple command is easy enough.

**Comment by Catgroove** [comment]
> What do you think of this
> 
> ```toml
> [[session]]
> name = "fish config"
> path = "~/c/dotfiles/.config/fish"
> disable_startup_command = true
> ```
> 
> It should be trivial to implement, but I think adding some sort of simple command is easy enough.

Looks good! More intuitive than leaving it empty, for sure, even though that's what I tried initially.

**Comment by joshmedeski** [comment]
Great, I'll add this as an official feature to be worked on soon.

As a user, I want to disable the default startup command, to avoid unwanted behavior for certain sessions and improve my workflow.

- [ ] Add a `disable_startup_command` option to the session configuration
- [ ] Skip the default startup command if the option is set to true on the selected config session

```toml
[[session]]
name = "fish config"
path = "~/c/dotfiles/.config/fish"
disable_startup_command = true
```

**Comment by zaynOm** [comment]
Is there a way to disable it for a normal path without adding it to the config sessions.

I tend to move to the root folder of my projects and I don't want it to open `nvim` nor to I wanna add it to config sessions
I tried this
```sh
[[session]]
path = '~/Projects'
disable_startup_command = true
```

**Comment by joshmedeski** [comment]
For now, there isn't a way to disable the default startup command on specific directories without creating a custom config. 

For now, you'll have to include the name:
```toml
[[session]]
name = 'Projects'
path = '~/Projects'
disable_startup_command = true
```

I'll think of some ideas for how we could approach a better configuration solution for this use case.
