### ISSUE TITLE
Configuration Imports no longer appear to work

### ISSUE THREAD

**Issue by acburdine** [joshmedeski/sesh#175]
### What happened?

Tried using sesh today for the first time, was working through some different configurations when I realized that the `import = ["./some/other/file"]` syntax appears to have been removed as part of the [v2 rewrite](https://github.com/joshmedeski/sesh/pull/142), though the configuration property still exists in the config model 🤔 

Happy to make a PR re-adding support for this, just thought I'd open an issue to track the work.

Example Configuration:
```toml
# sesh.toml
[[session]]
name = "dotfiles"
path = "~/dotfiles"
startup_command = "nvim ."

import = ["~/.config/sesh/sesh-2.toml"]
```

```toml
# sesh-2.toml
[[session]]
name = "test"
path = "/tmp"
startup_command = "ls -al"
```

```sh
❯ sesh list -c
dotfiles
```

### Version

2.3.1

### Reviewed

- [X] Reviewed existing issues and made sure this bug has not already been submitted.
- [X] I have read the documentation and understand how sesh works before submitting this bug
