### ISSUE TITLE
Session.window in sesh.toml

### ISSUE THREAD

**Issue by SebastianBalle** [joshmedeski/sesh#201]
### What would you like sesh to do?

Hi Josh

First of all thanks for a cool session manager! I want to hear if you have thought about implementing session windows in the `sesh.toml` file such that you can automatically create sessions with multiple windows inside. It could have the following example structure

```toml
  [[session]]
  name = "sesh"
  path = "~"
  startup_command = "nvim ."

  [[session.window]]
  session = "sesh"
  name = "zsh"

  [[session.window]]
  session = "sesh"
  name = "Service1"
  startup_command = "nix develop && task service1"
```

Let me know what you think or if this is too big of a feature request for now.

I have been quite inspired by your dotfiles in my [Nix dotfiles setup](https://github.com/SebastianBalle/dotfiles/blob/main/home/features/programs/sesh.nix) but hope to see sesh as part of home-manager soon as well. 😉
