### ISSUE TITLE
Configure Sorting

### ISSUE THREAD

**Issue by joshmedeski** [joshmedeski/sesh#208]
### What would you like sesh to do?

As a user, I want to configure how the list will return groups by customizing the order.

Here is my initial idea for how this might look:
```toml
[list]
sort_order = ['tmux', 'tmuxinator', 'config', 'zoxide']
```

Things to keep in mind:
- If new groups are introduced, it's important to recognize that it would require the user to manually add that to their list
- Typos would potentially cause things to crash or not work as expected
