### ISSUE TITLE
How to configure the blacklist ?

### ISSUE THREAD

**Issue by Hurricaane** [joshmedeski/sesh#221]
I don't know if I'm missing something but I can't configure the blacklist correctly.. Where do I add it exactly ?

My config : 

```toml
[default_session]
preview_command = "eza --long --header --icons --all --git --color=always {}"
blacklist = ["scratch"]

[[session]]
name = "home"
path = "~"
disable_startup_command = true

[[session]]
name = "dotfiles"
path = "~/dotfiles"
startup_command = "lazygit"

[[session]]
name = "downloads"
path = "~/Downloads"
startup_command = "y"

[[session]]
name = "tmux config"
path = "~/dotfiles/tmux"
startup_command = "nvim tmux.conf"
preview_command = "bat --color=always ~/dotfiles/tmux/tmux.conf"

[[session]]
name = "neovim config"
path = "~/dotfiles/neovims/LazyVim"
startup_command = "nvim"

[[session]]
name = "sesh config"
path = "~/.config/sesh"
startup_command = "nvim sesh.toml"
preview_command = "bat --color=always ~/.config/sesh/sesh.toml"

[[session]]
name = "yazi config"
path = "~/.config/yazi"
startup_command = "nvim yazi.toml"
preview_command = "bat --color=always ~/.config/yazi/yazi.toml"

[[session]]
name = "hyprland config"
path = "~/.config/hypr"
```

When I use my sesh keybinding : 
![Image](https://github.com/user-attachments/assets/ab2be0cc-9a5f-4591-9700-ad9db1e9faed)
