### ISSUE TITLE
Allow `session_path` to be configured with wildcards (e.g. `~/projects/project-*` or `~/projects/*`)

### ISSUE THREAD

**Issue by wbeeftink** [joshmedeski/sesh#80]
### What would you like sesh to do?

I would like `session_path` to allow wildcards so I can use the same `script_path` for similar projects.

I have several projects where I typically like to open a few windows (code, server, tests, zsh). What I do now, is define a startup script per project pointing to the same `script_path`.

```toml
[[startup_scripts]]
script_path = "~/.config/sesh/scripts/project"
session_path = "~/projects/project-1"

[[startup_scripts]]
script_path = "~/.config/sesh/scripts/project"
session_path = "~/projects/project-2"
```

With a wildcard this could be reduced to something like this:

```toml
[[startup_scripts]]
script_path = "~/.config/sesh/scripts/project"
session_path = "~/projects/project-*"
```

Or something like this?

```toml
[[startup_scripts]]
script_path = "~/.config/sesh/scripts/project"
session_path = "~/projects/*"
```

Apologies if this is already possible and I missed something in the docs.

For reference, this is what my startup script contains:

```sh
#!/usr/bin/env bash
# vi: ft=sh

tmux rename-window "code"
tmux new-window -n "server"
tmux new-window -n "tests"
tmux new-window
tmux select-window -t 1
nvim -c "Telescope find_files"
```
