### ISSUE TITLE
Session Config

### ISSUE THREAD

**Issue by joshmedeski** [joshmedeski/sesh#86]
### What would you like sesh to do?

Add the ability to configure a session:

```toml
[[startup_scripts]]
session_path = "~/c/joshmedeski.com"
script_path = "~/.config/sesh/scripts/node_dev"
```

Becomes...

```toml
[[session]]
path = "~/c/joshmedeski.com"
name = "👨‍🏫 joshmedeski.com"
# startup_script or startup_command is allowed
startup_script = "~/.config/sesh/scripts/node_dev"
startup_command="nvim ./src/index.ts"
```

Note, this will work great alongside #84. Furthermore, we could detect a `sesh.toml` file in the session path to determine these same config options, possibly allowing paths to be relative.

```toml
[[session]]
path = "./src/content/posts"
name = "✍️ posts (joshmedeski.com)"
startup_command="nvim +GoToFile"
```

However, this could slow down all session start times as it would need to scan the file structure every time.
