### ISSUE TITLE
different session configs with the same path only execute for the first one

### ISSUE THREAD

**Issue by barrydevp** [joshmedeski/sesh#97]
### What happened?

When I config some sessions with the same path directory:
```toml
[[session]]
name = "update nvim"
path = "/tmp"
startup_command = "brew upgrade neovim --fetch-HEAD && exit"

[[session]]
name = "update all"
path = "/tmp"
startup_command = "brew update && brew upgrade && exit"
```
I expected `update nvim` and `update all` to run their own session but only `update nvim` was executed regardless of session!

### Version

1.1.0

### Reviewed

- [X] Reviewed existing issues and made sure this bug has not already been submitted.
- [X] I have read the documentation and understand how sesh works before submitting this bug

**Comment by barrydevp** [comment]
correct me if I'm wrong, but I think we should return the found session config command here and pass it to `connect` function.
https://github.com/joshmedeski/sesh/blob/fe6e6a65d8cb9dbc2f0ab5abdbe15351c5504d96/session/determine.go#L16C4-L20C5

**Comment by joshmedeski** [comment]
I am actively reworking the connect logic to handle this situation, thanks for flagging this. The first version of sesh was very much dependent on determining the path first, so this new config pattern breaks that pattern.

I'll be sure to mark this issue closed when I complete the work.

**Comment by mloskot** [comment]
I think I have just realised my setup is suffering from this issue too. My `sesh.toml` has two sessions configured to switch between `qlt` and `tst` cloud environments for which Infra-as-Code is maintained in the common Git repository:

```ini
[[session]]
name = "qlt"
path = "~/azure-hosting"
startup_script = "~/.config/sesh/scripts/azure-hosting-qlt.sh"

[[session]]
name = "tst"
path = "~/azure-hosting"
startup_script = "~/.config/sesh/scripts/azure-hosting-tst.sh"
```

The `sesh connect tst` does not load `tst` environment session, but seems to load the first one in the config, that is `sesh connect qlt`.

**Comment by joshmedeski** [comment]
This should be fixed in sesh v2, There's a beta release if you want to test it. The full release is coming in a couple of weeks!

**Comment by mloskot** [comment]
I'm happy to confirm the issue I described in https://github.com/joshmedeski/sesh/issues/97#issuecomment-2280724523 has now been fixed - I just had to `s/startup_script/startup_command/`. Thank you @joshmedeski for v2.0!

**Comment by joshmedeski** [comment]
The startup command will only match by name (not path) so the issue is fixed with the v2 launch!

**Comment by mloskot** [comment]
@joshmedeski Late August I confirmed the fix https://github.com/joshmedeski/sesh/issues/97#issuecomment-2307078446 works for me. I've just upgraded to latest `sesh version dev` and I'm observing the problem is back and this `sesh.toml` I've been using is no longer switching to `azure-hosting-tst` but always loads and connects `azure-hosting-prd`

```toml
[[session]]
name = "azure-hosting-prd"
path = "~/azure-hosting"
startup_command = "~/.config/sesh/scripts/azure-hosting-prd.sh"

[[session]]
name = "azure-hosting-qlt"
path = "~/azure-hosting"
startup_command = "~/.config/sesh/scripts/azure-hosting-qlt.sh"

[[session]]
name = "azure-hosting-tst"
path = "~/azure-hosting"
startup_command = "~/.config/sesh/scripts/azure-hosting-tst.sh"
```

Interestingly, if I downgrade from `sesh version dev` to `sesh version 2.4.0` then everything works for me again.

IMHO, this issue needs to be re-opened.
